{% set name = "spacy-loggers" %}
{% set modulename = "spacy_loggers" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17d0e249b2e6c6546c49fc6561a0a685f91a8edbf24a5b2b7759ead443c74654

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - wasabi >=0.8.1,<1.1.0

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - spacy >=3.1
  commands:
    - python -m pytest --tb=native --pyargs {{ modulename }}


about:
  home: https://github.com/explosion/spacy-loggers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate loggers for spaCy pipeline training
  description: Enables alternatives to spaCy's built-in console logger
  doc_url: https://github.com/explosion/spacy-loggers
  dev_url: https://github.com/explosion/spacy-loggers

extra:
  recipe-maintainers:
    - honnibal
    - ines
    - rspeer
    - adrianeboyd
