{% set name = "spacy-loggers" %}
{% set modulename = "spacy_loggers" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d60b0bdbf915a60e516cc2e653baeff946f0cfc461b452d11a4d5458c6fe5f24

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - {{ modulename }}
  requires:
    - pytest
    - spacy >=3.1
    - python {{ python_min }}
  commands:
    - python -m pytest --tb=native --pyargs {{ modulename }}


about:
  home: https://github.com/explosion/spacy-loggers
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Alternate loggers for spaCy pipeline training
  description: Enables alternatives to spaCy's built-in console logger
  doc_url: https://github.com/explosion/spacy-loggers
  dev_url: https://github.com/explosion/spacy-loggers

extra:
  recipe-maintainers:
    - conda-forge/spacy
